AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - '**/*_spec.rb'
    - 'zen-search.gemspec'
    - 'lib/zen/search/cli.rb'

Style/ClassAndModuleChildren:
  Enabled: false
Lint/BooleanSymbol:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
  Exclude:
     - 'lib/zen/search/services/print.rb'

Metrics/CyclomaticComplexity:
  Exclude: 
    - 'lib/zen/search/services/print.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/zen/search/services/print.rb'

