#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "zen/search"

cli = Zen::Search::CLI.new

puts "Welcome to Zendesk Search"
puts "Select 'quit' to exit at any time, Press 'Enter' to continue with option selected"
puts "\n\n"

begin
  files = ['data/users.json', 'data/tickets.json']
  cli.run(files)
rescue Errno::ENOENT => e
  puts e.message.to_s
end